...F...F
======================================================================
FAIL: test_netflix_eval_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 75, in test_netflix_eval_1
    self.assertEqual(user_prediction, 3.7)
AssertionError: 4.070170693749583 != 3.7

======================================================================
FAIL: test_netflix_solve_1 (__main__.TestNetflix)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "TestNetflix.py", line 85, in test_netflix_solve_1
    self.assertEqual(w.getvalue(), "1:\n3.7\n3.5\n3.6\n")
AssertionError: '1:\n4.070170693749583\n3.6940913419960815\n3.9830949740761827\n' != '1:\n3.7\n3.5\n3.6\n'
  1:
- 4.070170693749583
- 3.6940913419960815
- 3.9830949740761827
+ 3.7
+ 3.5
+ 3.6


----------------------------------------------------------------------
Ran 8 tests in 0.002s

FAILED (failures=2)
RMSE: 0.6
